[package]
name = "wasm_task"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
serde_json ="1.0.111"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"